name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: shellcheck update-proton.sh install.sh

    - name: Install
      run: make install

    - name: Call command for usage information
      run: update-proton -h

    - name: Dry run
      run: DRY_RUN=true update-proton pass

    - name: Uninstall
      run: make uninstall
